version: '3'
services:
  userapi:
    build: .
    image: user-api
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - DB_DOMAIN=mongo
  mongo:
    image: mongo
    volumes:
      - $PWD/data:/data/db