version: 2
jobs:
  build:
    docker:
      - image: tmaier/docker-compose
    working_directory: ~/my-app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Tests
          command: cd api && docker-compose -f docker-compose.test.yml up --exit-code-from userapi
      
      - run:
          name: Publish
          command: |
            cd api
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t "joaopio/user-api" .
            docker push joaopio/user-api:latest
