version: 2
jobs:
  build:
    docker:
      - image: tmaier/docker-compose
    working_directory: ~/my-app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Tests
          command: cd api && docker-compose -f docker-componse.test.yml up --exit-code-from userapi
      
      - run:
          name: Build
          command: cd api && docker build -t "joao-pio/userapi" .