language: node_js

node_js:
  - 9.3.0

services:
  - docker

after_success:
  - docker build -t joaopio/user-api .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push joaopio/user-api
