version: '3'
services:
  userapi:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: user-api-test
    depends_on:
      - mongo
    environment:
      - DB_DOMAIN=mongo
    networks:
      - userapinetwork
  mongo:
    image: mongo
    networks:
      - userapinetwork
networks:
  userapinetwork:
