version: '3'
services:
  userapi:
    build: .
    image: user-api
    depends_on:
      - mongo
    environment:
      - DB_DOMAIN=mongo
    networks:
      - socialnetwork
      - userapinetwork
    ports:
      - 3000:3000
  mongo:
    image: mongo
    networks:
      - userapinetwork
networks:
  socialnetwork:
    external: true
  userapinetwork:
